name: terraform module

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Plan or Apply'
        options:
          - Plan
          - Apply
          - Destroy
        required: true
        default: 'Plan'
      
      vars_files:
        type: choice
        description: 'Path to vars files'
        options: 
          - dev.tfvars
          - prod.tfvars
          - stage.tfvars
        required: true
        default: 'dev.tfvars'

jobs:
  terraform:
    permissions:
      id-token: write  
      contents: read  

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: ssh
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.CI_ROLE }}    
                  
      - name: init
        run: terraform init

      - name: validate
        run: terraform validate

      - name: format
        run: terraform fmt -recursive

      - name: plan
        run: terraform ${{ github.event.inputs.action }} -var-file=${{ github.event.inputs.vars_files}}
        if: ${{ github.event.inputs.action == 'plan' }}

      - name: apply
        run: terraform ${{ github.event.inputs.action }} -var-file=${{ github.event.inputs.vars_files}} -auto-approve
        if: ${{ github.event.inputs.action == 'apply' }}